[package]
name = "flashlight"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.10", features = ["derive"] }
console = "0.15.7"
ignore = "0.4.20"
swc_common = "0.31.16"
swc_ecma_ast = "0.106.6"
swc_ecma_parser = "0.136.8"
